INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (1, 'Ciąża');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (2, 'Złamanie ręki');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (3, 'Złamanie nogi');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (4, 'Złamanie kręgosłupa');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (5, 'Złamanie szyi');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (6, 'Złamanie palca');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (7, 'Padaczka');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (8, 'Stwardnienie zanikowe boczne');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (9, 'Choroba i zespół Parkinsona');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (10, 'Choroba Alzheimera');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (11, 'Choroba Huntingtona');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (12, 'Choroba Creutzfeldta-Jakoba');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (13, 'Zespół Guillaina-Barrégo');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (14, 'Stwardnienie rozsiane');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (15, 'Migrena');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (16, 'Klasterowy ból głowy');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (17, 'Udar mózgu');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (18, 'Zapalenie opon mózgowych');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (19, 'Encefalopatia wątrobowa');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (20, 'Kiła');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (21, 'Rzeżączka');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (22, 'Chlamydiozy');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (23, 'Wrzód weneryczny');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (24, 'Czerwonka bakteryjna');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (25, 'Ziarniniak pachwinowy');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (26, 'Mycoplasma genitalium');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (27, 'AIDS');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (28, 'Opryszczka genitaliów, opryszczka wargowa');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (29, 'WZW');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (30, 'Kłykciny kończyste');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (31, 'HTLV');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (32, 'Kandydoza');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (33, 'Rzęsistkowica');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (34, 'Świerzb');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (35, 'Wszawica łonowa');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (36, 'Ameboza');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (37, 'Toczeń rumieniowaty układowy');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (38, 'Twardzina');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (39, 'Układowe zapalenia naczyń');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (40, 'Reumatoidalne zapalenie stawów');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (41, 'Reaktywne zapalenie stawów');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (42, 'Zesztywniające zapalenie stawów kręgosłupa');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (43, 'Łuszczycowe zapalenie stawów');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (44, 'Miażdżyca');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (45, 'Choroba niedokrwienna serca');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (46, 'Zaburzenia rytmu i przewodzenia');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (47, 'Wady serca (wrodzone i nabyte)');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (48, 'Choroby wsierdzia');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (49, 'Choroby mięśnia sercowego');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (50, 'Choroby osierdzia');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (51, 'Nowotwór serca');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (52, 'Niewydolność serca');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (53, 'Nadciśnienie tętnicze');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (54, 'Nadciśnienie płucne');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (55, 'Choroby aorty i naczyń obwodowych');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (56, 'Choroby żył obwodowych');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (57, 'Żylna choroba zakrzepowo-zatorowa');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (58, 'Choroby mikrokrążenia');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (59, 'Choroby naczyń chłonnych');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (60, 'Jęczmyk');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (61, 'Ropień powieki');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (62, 'Półpasiec powieki i gałki ocznej');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (63, 'Ospica');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (64, 'Zapalenie brzegów powiek');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (65, 'Kępki żółte');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (66, 'Brodawka powieki');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (67, 'Naczyniak powieki');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (68, 'Rak powieki');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (69, 'Niedomykalność szpary powiekowej');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (70, 'Wywinięcie powieki');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (71, 'Podwinięcie powieki');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (72, 'Nieprawidłowy wzrost rzęs');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (73, 'Tik powieki');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (74, 'Nadmierne częste mruganie');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (75, 'Akrofobia');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (76, 'Alkoholowy zespół abstynencyjny');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (77, 'Anhedonia');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (78, 'Anoreksja');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (79, 'Anxiety neurosis');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (80, 'Autyzm');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (81, 'Bezsenność');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (82, 'Błędne koło');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (83, 'Bulimia');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (84, 'Choroba afektywna');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (85, 'Choroba sieroca');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (86, 'Ciąża rzekoma');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (87, 'Depresja');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (88, 'Depresja poporodowa');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (89, 'Dysgrafia');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (90, 'Dyskalkulia rozwojowa');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (91, 'Dysortografia');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (92, 'Dystymia');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (93, 'Egocentryzm');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (94, 'Fobia');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (95, 'Hipochondria');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (96, 'Histeria');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (97, 'Homofobia');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (98, 'Jadłowstręt psychiczny');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (99, 'Klaustrofobia');
INSERT INTO wydarzenia_medyczne (id_wydarzenia, nazwa) VALUES (100, 'Lęk');