INSERT INTO cele_wizyty (nazwa) VALUES ('Profilaktyka');
INSERT INTO cele_wizyty (nazwa) VALUES ('Bronchoskopia');
INSERT INTO cele_wizyty (nazwa) VALUES ('Laryngoskopia');
INSERT INTO cele_wizyty (nazwa) VALUES ('Stroboskopia');
INSERT INTO cele_wizyty (nazwa) VALUES ('Gastroskopia');
INSERT INTO cele_wizyty (nazwa) VALUES ('Ezofagoskopia');
INSERT INTO cele_wizyty (nazwa) VALUES ('Panendoskopia');
INSERT INTO cele_wizyty (nazwa) VALUES ('Gastroduodenoskopia');
INSERT INTO cele_wizyty (nazwa) VALUES ('Duodenoskopia');
INSERT INTO cele_wizyty (nazwa) VALUES ('Intestinoskopia');
INSERT INTO cele_wizyty (nazwa) VALUES ('Kolonoskopia');
INSERT INTO cele_wizyty (nazwa) VALUES ('Anoskopia');
INSERT INTO cele_wizyty (nazwa) VALUES ('Rektoskopia');
INSERT INTO cele_wizyty (nazwa) VALUES ('Rektoromanoskopia');
INSERT INTO cele_wizyty (nazwa) VALUES ('Sigmoidoskopia');
INSERT INTO cele_wizyty (nazwa) VALUES ('Endoskopia kapsułkowa');
INSERT INTO cele_wizyty (nazwa) VALUES ('Kolposkopia');
INSERT INTO cele_wizyty (nazwa) VALUES ('Cystoskopia');
INSERT INTO cele_wizyty (nazwa) VALUES ('Laparoskopia');
INSERT INTO cele_wizyty (nazwa) VALUES ('Endoskopia igłowa');
INSERT INTO cele_wizyty (nazwa) VALUES ('Abdominoplastyka');
INSERT INTO cele_wizyty (nazwa) VALUES ('Adenotomia');
INSERT INTO cele_wizyty (nazwa) VALUES ('Adenomektomia');
INSERT INTO cele_wizyty (nazwa) VALUES ('Adrenalektomia');
INSERT INTO cele_wizyty (nazwa) VALUES ('Amputacja');
INSERT INTO cele_wizyty (nazwa) VALUES ('Angioplastyka');
INSERT INTO cele_wizyty (nazwa) VALUES ('Antromastoidektomia');
INSERT INTO cele_wizyty (nazwa) VALUES ('Appendektomia');
INSERT INTO cele_wizyty (nazwa) VALUES ('Artroskopia');
INSERT INTO cele_wizyty (nazwa) VALUES ('Astragalektomia');
INSERT INTO cele_wizyty (nazwa) VALUES ('Bronchotomia');
INSERT INTO cele_wizyty (nazwa) VALUES ('Cholecystektomia');
INSERT INTO cele_wizyty (nazwa) VALUES ('Cystogastrostomia');
INSERT INTO cele_wizyty (nazwa) VALUES ('Dekortykacja płuca');
INSERT INTO cele_wizyty (nazwa) VALUES ('Diwertikulotomia');
INSERT INTO cele_wizyty (nazwa) VALUES ('Fundoplastyka');
INSERT INTO cele_wizyty (nazwa) VALUES ('Gastrektomia');
INSERT INTO cele_wizyty (nazwa) VALUES ('Hemikorporektomia');
INSERT INTO cele_wizyty (nazwa) VALUES ('Heminefrektomia');
INSERT INTO cele_wizyty (nazwa) VALUES ('Hemisferektomia');
INSERT INTO cele_wizyty (nazwa) VALUES ('Hepatektomia');
INSERT INTO cele_wizyty (nazwa) VALUES ('Hipofizektomia');
INSERT INTO cele_wizyty (nazwa) VALUES ('Histerektomia');
INSERT INTO cele_wizyty (nazwa) VALUES ('Irydektomia');
INSERT INTO cele_wizyty (nazwa) VALUES ('Kalozotomia');
INSERT INTO cele_wizyty (nazwa) VALUES ('Kolektomia');
INSERT INTO cele_wizyty (nazwa) VALUES ('Kraniektomia');
INSERT INTO cele_wizyty (nazwa) VALUES ('Kraniotomia');
INSERT INTO cele_wizyty (nazwa) VALUES ('Laminektomia');
INSERT INTO cele_wizyty (nazwa) VALUES ('Laryngektomia');
INSERT INTO cele_wizyty (nazwa) VALUES ('Laryngofisura');
INSERT INTO cele_wizyty (nazwa) VALUES ('Ligacja jajowodu');
INSERT INTO cele_wizyty (nazwa) VALUES ('Litotrypsja');
INSERT INTO cele_wizyty (nazwa) VALUES ('Lobektomia');
INSERT INTO cele_wizyty (nazwa) VALUES ('Lobotomia');
INSERT INTO cele_wizyty (nazwa) VALUES ('Mastektomia');
INSERT INTO cele_wizyty (nazwa) VALUES ('Metastazektomia');
INSERT INTO cele_wizyty (nazwa) VALUES ('Mukosektomia');
INSERT INTO cele_wizyty (nazwa) VALUES ('Nacięcie krocza');
INSERT INTO cele_wizyty (nazwa) VALUES ('Nefrektomia');
INSERT INTO cele_wizyty (nazwa) VALUES ('Nefrotomia');
INSERT INTO cele_wizyty (nazwa) VALUES ('Obrzezanie');
INSERT INTO cele_wizyty (nazwa) VALUES ('Ooforektomia');
INSERT INTO cele_wizyty (nazwa) VALUES ('Operacja Bassiniego');
INSERT INTO cele_wizyty (nazwa) VALUES ('Operacja Billrotha');
INSERT INTO cele_wizyty (nazwa) VALUES ('Operacja Brickera');
INSERT INTO cele_wizyty (nazwa) VALUES ('Operacja Drapanasa');
INSERT INTO cele_wizyty (nazwa) VALUES ('Operacja Girarda');
INSERT INTO cele_wizyty (nazwa) VALUES ('Operacja Halstedta');
INSERT INTO cele_wizyty (nazwa) VALUES ('Operacja Hartmanna');
INSERT INTO cele_wizyty (nazwa) VALUES ('Operacja Jurasza');
INSERT INTO cele_wizyty (nazwa) VALUES ('Operacja Lichtensteina');
INSERT INTO cele_wizyty (nazwa) VALUES ('Operacja Milesa');
INSERT INTO cele_wizyty (nazwa) VALUES ('Operacja Mogga');
INSERT INTO cele_wizyty (nazwa) VALUES ('Operacja Nussa');
INSERT INTO cele_wizyty (nazwa) VALUES ('Operacja Puestowa');
INSERT INTO cele_wizyty (nazwa) VALUES ('Operacja Rutkowa');
INSERT INTO cele_wizyty (nazwa) VALUES ('Operacja Rydygiera');
INSERT INTO cele_wizyty (nazwa) VALUES ('Operacja Warrena');
INSERT INTO cele_wizyty (nazwa) VALUES ('Operacja Whipple’a');
INSERT INTO cele_wizyty (nazwa) VALUES ('Operacja zmiany płci');
INSERT INTO cele_wizyty (nazwa) VALUES ('Orbitotomia');
INSERT INTO cele_wizyty (nazwa) VALUES ('Orchidektomia');
INSERT INTO cele_wizyty (nazwa) VALUES ('Owarektomia');
INSERT INTO cele_wizyty (nazwa) VALUES ('Owariektomia');
INSERT INTO cele_wizyty (nazwa) VALUES ('Papilotomia');
INSERT INTO cele_wizyty (nazwa) VALUES ('Paracenteza');
INSERT INTO cele_wizyty (nazwa) VALUES ('Pankreatoduodenektomia');
INSERT INTO cele_wizyty (nazwa) VALUES ('Penektomia');
INSERT INTO cele_wizyty (nazwa) VALUES ('Perikardiektomia');
INSERT INTO cele_wizyty (nazwa) VALUES ('Plastyka Heinekego-Mikulicza');
INSERT INTO cele_wizyty (nazwa) VALUES ('Prostatektomia');