INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (1, 1, 19, 11, 'Kolonoskopia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (2, 2, 11, 31, 'Bronchotomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (3, 3, 5, 15, 'Sigmoidoskopia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (4, 4, 17, 25, 'Amputacja');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (5, 5, 13, 58, 'Mukosektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (6, 6, 4, 24, 'Adrenalektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (7, 7, 4, 40, 'Hemisferektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (8, 8, 8, 91, 'Plastyka Heinekego-Mikulicza');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (9, 9, 16, 41, 'Hepatektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (10, 10, 22, 76, 'Operacja Puestowa');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (11, 11, 6, 86, 'Papilotomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (12, 12, 9, 35, 'Diwertikulotomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (13, 13, 9, 38, 'Hemikorporektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (14, 14, 6, 72, 'Operacja Lichtensteina');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (15, 15, 11, 3, 'Laryngoskopia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (16, 16, 4, 34, 'Dekortykacja płuca');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (17, 17, 8, 81, 'Operacja zmiany płci');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (18, 18, 7, 31, 'Bronchotomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (19, 19, 7, 45, 'Kalozotomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (20, 20, 6, 45, 'Kalozotomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (21, 21, 2, 85, 'Owariektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (22, 22, 2, 13, 'Rektoskopia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (23, 23, 16, 61, 'Nefrotomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (24, 24, 17, 10, 'Intestinoskopia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (25, 25, 2, 15, 'Sigmoidoskopia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (26, 26, 20, 83, 'Orchidektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (27, 27, 10, 43, 'Histerektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (28, 28, 19, 5, 'Gastroskopia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (29, 29, 17, 77, 'Operacja Rutkowa');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (30, 30, 11, 16, 'Endoskopia kapsułkowa');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (31, 31, 5, 36, 'Fundoplastyka');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (32, 32, 15, 72, 'Operacja Lichtensteina');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (33, 33, 8, 7, 'Panendoskopia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (34, 34, 15, 86, 'Papilotomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (35, 35, 10, 28, 'Appendektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (36, 36, 20, 20, 'Endoskopia igłowa');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (37, 37, 1, 52, 'Ligacja jajowodu');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (38, 38, 10, 20, 'Endoskopia igłowa');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (39, 39, 1, 2, 'Bronchoskopia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (40, 40, 15, 79, 'Operacja Warrena');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (41, 41, 22, 67, 'Operacja Drapanasa');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (42, 42, 21, 80, 'Operacja Whipple’a');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (43, 43, 11, 28, 'Appendektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (44, 44, 3, 89, 'Penektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (45, 45, 6, 20, 'Endoskopia igłowa');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (46, 46, 8, 49, 'Laminektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (47, 47, 13, 36, 'Fundoplastyka');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (48, 48, 4, 69, 'Operacja Halstedta');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (49, 49, 6, 74, 'Operacja Mogga');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (50, 50, 12, 55, 'Lobotomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (51, 51, 7, 76, 'Operacja Puestowa');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (52, 52, 11, 40, 'Hemisferektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (53, 53, 14, 48, 'Kraniotomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (54, 54, 12, 46, 'Kolektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (55, 55, 6, 4, 'Stroboskopia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (56, 56, 13, 75, 'Operacja Nussa');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (57, 57, 7, 1, 'Profilaktyka');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (58, 58, 20, 79, 'Operacja Warrena');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (59, 59, 15, 42, 'Hipofizektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (60, 60, 21, 58, 'Mukosektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (61, 61, 15, 5, 'Gastroskopia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (62, 62, 20, 3, 'Laryngoskopia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (63, 63, 21, 85, 'Owariektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (64, 64, 19, 69, 'Operacja Halstedta');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (65, 65, 4, 85, 'Owariektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (66, 66, 4, 23, 'Adenomektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (67, 67, 5, 59, 'Nacięcie krocza');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (68, 68, 16, 65, 'Operacja Billrotha');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (69, 69, 14, 57, 'Metastazektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (70, 70, 10, 30, 'Astragalektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (71, 71, 8, 45, 'Kalozotomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (72, 72, 11, 70, 'Operacja Hartmanna');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (73, 73, 15, 76, 'Operacja Puestowa');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (74, 74, 14, 17, 'Kolposkopia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (75, 75, 13, 87, 'Paracenteza');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (76, 76, 9, 70, 'Operacja Hartmanna');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (77, 77, 20, 20, 'Endoskopia igłowa');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (78, 78, 14, 63, 'Ooforektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (79, 79, 22, 86, 'Papilotomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (80, 80, 10, 52, 'Ligacja jajowodu');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (81, 81, 15, 61, 'Nefrotomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (82, 82, 19, 71, 'Operacja Jurasza');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (83, 83, 6, 86, 'Papilotomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (84, 84, 3, 61, 'Nefrotomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (85, 85, 10, 54, 'Lobektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (86, 86, 15, 70, 'Operacja Hartmanna');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (87, 87, 19, 32, 'Cholecystektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (88, 88, 15, 37, 'Gastrektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (89, 89, 11, 84, 'Owarektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (90, 90, 12, 6, 'Ezofagoskopia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (91, 91, 12, 22, 'Adenotomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (92, 92, 8, 51, 'Laryngofisura');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (93, 93, 8, 85, 'Owariektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (94, 94, 11, 69, 'Operacja Halstedta');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (95, 95, 11, 18, 'Cystoskopia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (96, 96, 7, 28, 'Appendektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (97, 97, 20, 25, 'Amputacja');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (98, 98, 18, 71, 'Operacja Jurasza');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (99, 99, 16, 51, 'Laryngofisura');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (100, 100, 18, 82, 'Orbitotomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (101, 101, 21, 21, 'Abdominoplastyka');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (102, 102, 12, 9, 'Duodenoskopia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (103, 103, 19, 14, 'Rektoromanoskopia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (104, 104, 12, 58, 'Mukosektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (105, 105, 9, 38, 'Hemikorporektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (106, 106, 1, 33, 'Cystogastrostomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (107, 107, 2, 1, 'Profilaktyka');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (108, 108, 7, 54, 'Lobektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (109, 109, 9, 39, 'Heminefrektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (110, 110, 14, 23, 'Adenomektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (111, 111, 4, 73, 'Operacja Milesa');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (112, 112, 18, 14, 'Rektoromanoskopia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (113, 113, 3, 36, 'Fundoplastyka');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (114, 114, 20, 16, 'Endoskopia kapsułkowa');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (115, 115, 18, 80, 'Operacja Whipple’a');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (116, 116, 18, 43, 'Histerektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (117, 117, 15, 64, 'Operacja Bassiniego');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (118, 118, 3, 85, 'Owariektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (119, 119, 21, 53, 'Litotrypsja');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (120, 120, 17, 7, 'Panendoskopia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (121, 121, 16, 31, 'Bronchotomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (122, 122, 16, 84, 'Owarektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (123, 123, 3, 27, 'Antromastoidektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (124, 124, 21, 40, 'Hemisferektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (125, 125, 1, 22, 'Adenotomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (126, 126, 18, 26, 'Angioplastyka');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (127, 127, 17, 65, 'Operacja Billrotha');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (128, 128, 21, 43, 'Histerektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (129, 129, 1, 65, 'Operacja Billrotha');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (130, 130, 15, 23, 'Adenomektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (131, 131, 20, 87, 'Paracenteza');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (132, 132, 20, 24, 'Adrenalektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (133, 133, 22, 19, 'Laparoskopia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (134, 134, 12, 74, 'Operacja Mogga');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (135, 135, 8, 27, 'Antromastoidektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (136, 136, 10, 35, 'Diwertikulotomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (137, 137, 14, 54, 'Lobektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (138, 138, 20, 35, 'Diwertikulotomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (139, 139, 19, 2, 'Bronchoskopia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (140, 140, 14, 65, 'Operacja Billrotha');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (141, 141, 13, 51, 'Laryngofisura');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (142, 142, 17, 57, 'Metastazektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (143, 143, 11, 36, 'Fundoplastyka');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (144, 144, 13, 54, 'Lobektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (145, 145, 13, 1, 'Profilaktyka');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (146, 146, 8, 9, 'Duodenoskopia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (147, 147, 4, 76, 'Operacja Puestowa');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (148, 148, 17, 21, 'Abdominoplastyka');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (149, 149, 21, 47, 'Kraniektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (150, 150, 22, 21, 'Abdominoplastyka');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (151, 151, 6, 32, 'Cholecystektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (152, 152, 19, 5, 'Gastroskopia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (153, 153, 11, 9, 'Duodenoskopia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (154, 154, 8, 4, 'Stroboskopia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (155, 155, 2, 67, 'Operacja Drapanasa');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (156, 156, 7, 25, 'Amputacja');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (157, 157, 1, 78, 'Operacja Rydygiera');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (158, 158, 15, 40, 'Hemisferektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (159, 159, 13, 71, 'Operacja Jurasza');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (160, 160, 14, 10, 'Intestinoskopia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (161, 161, 9, 80, 'Operacja Whipple’a');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (162, 162, 1, 41, 'Hepatektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (163, 163, 18, 32, 'Cholecystektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (164, 164, 16, 87, 'Paracenteza');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (165, 165, 21, 29, 'Artroskopia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (166, 166, 15, 47, 'Kraniektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (167, 167, 14, 88, 'Pankreatoduodenektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (168, 168, 10, 85, 'Owariektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (169, 169, 10, 84, 'Owarektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (170, 170, 20, 63, 'Ooforektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (171, 171, 17, 60, 'Nefrektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (172, 172, 5, 65, 'Operacja Billrotha');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (173, 173, 8, 55, 'Lobotomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (174, 174, 18, 25, 'Amputacja');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (175, 175, 21, 6, 'Ezofagoskopia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (176, 176, 18, 70, 'Operacja Hartmanna');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (177, 1, 9, 52, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (178, 2, 4, 56, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (179, 3, 20, 68, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (180, 4, 7, 72, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (181, 5, 22, 8, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (182, 6, 6, 1, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (183, 7, 8, 6, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (184, 8, 20, 48, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (185, 9, 11, 14, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (186, 10, 2, 89, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (187, 11, 18, 11, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (188, 12, 1, 16, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (189, 13, 2, 27, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (190, 14, 15, 75, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (191, 15, 1, 50, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (192, 16, 15, 40, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (193, 17, 3, 74, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (194, 18, 1, 91, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (195, 19, 12, 30, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (196, 20, 17, 45, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (197, 21, 9, 1, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (198, 22, 11, 70, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (199, 23, 2, 37, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (200, 24, 7, 51, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (201, 25, 12, 34, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (202, 26, 12, 31, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (203, 27, 11, 52, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (204, 28, 11, 53, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (205, 29, 19, 13, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (206, 30, 9, 82, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (207, 31, 15, 2, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (208, 32, 7, 71, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (209, 33, 19, 32, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (210, 34, 17, 33, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (211, 35, 15, 48, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (212, 36, 19, 7, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (213, 37, 12, 31, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (214, 38, 19, 55, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (215, 39, 16, 10, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (216, 40, 4, 25, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (217, 41, 11, 62, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (218, 42, 14, 87, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (219, 43, 5, 9, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (220, 44, 12, 6, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (221, 45, 6, 81, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (222, 46, 21, 83, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (223, 47, 20, 24, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (224, 48, 15, 66, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (225, 49, 14, 40, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (226, 50, 2, 24, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (227, 51, 21, 83, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (228, 52, 8, 43, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (229, 53, 6, 14, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (230, 54, 2, 88, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (231, 55, 6, 19, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (232, 56, 5, 65, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (233, 57, 20, 76, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (234, 58, 15, 8, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (235, 59, 21, 14, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (236, 60, 4, 13, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (237, 61, 1, 8, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (238, 62, 1, 86, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (239, 63, 8, 66, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (240, 64, 15, 86, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (241, 65, 3, 65, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (242, 66, 4, 8, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (243, 67, 14, 46, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (244, 68, 13, 77, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (245, 69, 15, 56, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (246, 70, 18, 82, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (247, 71, 18, 1, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (248, 72, 13, 62, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (249, 73, 19, 22, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (250, 74, 17, 68, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (251, 75, 9, 83, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (252, 76, 20, 38, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (253, 77, 22, 85, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (254, 78, 8, 30, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (255, 79, 14, 90, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (256, 80, 6, 70, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (257, 81, 15, 40, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (258, 82, 19, 27, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (259, 83, 21, 35, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (260, 84, 3, 53, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (261, 85, 22, 84, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (262, 86, 10, 73, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (263, 87, 21, 4, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (264, 88, 10, 69, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (265, 89, 6, 19, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (266, 90, 11, 60, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (267, 91, 3, 34, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (268, 92, 2, 7, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (269, 93, 7, 37, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (270, 94, 9, 83, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (271, 95, 9, 59, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (272, 96, 15, 6, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (273, 97, 2, 45, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (274, 98, 8, 92, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (275, 99, 20, 43, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (276, 100, 13, 79, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (277, 101, 9, 2, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (278, 102, 14, 27, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (279, 103, 2, 9, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (280, 104, 1, 30, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (281, 105, 7, 48, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (282, 106, 22, 36, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (283, 107, 20, 3, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (284, 108, 11, 14, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (285, 109, 10, 78, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (286, 110, 1, 74, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (287, 111, 11, 65, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (288, 112, 19, 51, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (289, 113, 5, 18, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (290, 114, 12, 5, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (291, 115, 15, 9, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (292, 116, 20, 3, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (293, 117, 3, 50, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (294, 118, 7, 15, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (295, 119, 14, 32, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (296, 120, 11, 84, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (297, 121, 19, 41, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (298, 122, 7, 67, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (299, 123, 11, 70, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (300, 124, 20, 82, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (301, 125, 14, 85, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (302, 126, 16, 8, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (303, 127, 14, 50, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (304, 128, 14, 74, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (305, 129, 17, 16, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (306, 130, 19, 36, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (307, 131, 6, 69, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (308, 132, 9, 34, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (309, 133, 7, 66, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (310, 134, 12, 83, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (311, 135, 2, 1, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (312, 136, 18, 84, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (313, 137, 10, 10, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (314, 138, 14, 84, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (315, 139, 19, 47, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (316, 140, 18, 43, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (317, 141, 10, 44, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (318, 142, 12, 5, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (319, 143, 1, 16, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (320, 144, 19, 69, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (321, 145, 8, 64, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (322, 146, 3, 55, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (323, 147, 10, 50, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (324, 148, 22, 66, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (325, 149, 6, 45, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (326, 150, 14, 29, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (327, 151, 11, 40, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (328, 152, 5, 86, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (329, 153, 12, 79, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (330, 154, 19, 37, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (331, 155, 8, 58, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (332, 156, 19, 73, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (333, 157, 3, 37, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (334, 158, 19, 11, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (335, 159, 13, 63, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (336, 160, 19, 83, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (337, 161, 9, 91, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (338, 162, 11, 75, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (339, 163, 12, 42, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (340, 164, 12, 72, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (341, 165, 21, 13, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (342, 166, 2, 40, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (343, 167, 13, 29, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (344, 168, 8, 10, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (345, 169, 4, 18, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (346, 170, 12, 48, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (347, 171, 18, 34, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (348, 172, 7, 85, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (349, 173, 17, 13, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (350, 174, 1, 30, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (351, 175, 18, 82, null);
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (352, 176, 5, 17, null);
ALTER SEQUENCE skierowania_nr_skierowania_seq RESTART 353;