INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Ciąża');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Złamanie ręki');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Złamanie nogi');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Złamanie kręgosłupa');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Złamanie szyi');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Złamanie palca');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Padaczka');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Stwardnienie zanikowe boczne');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Choroba i zespół Parkinsona');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Choroba Alzheimera');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Choroba Huntingtona');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Choroba Creutzfeldta-Jakoba');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Zespół Guillaina-Barrégo');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Stwardnienie rozsiane');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Migrena');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Klasterowy ból głowy');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Udar mózgu');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Zapalenie opon mózgowych');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Encefalopatia wątrobowa');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Kiła');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Rzeżączka');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Chlamydiozy');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Wrzód weneryczny');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Czerwonka bakteryjna');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Ziarniniak pachwinowy');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Mycoplasma genitalium');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'AIDS');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Opryszczka genitaliów, opryszczka wargowa');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'WZW');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Kłykciny kończyste');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'HTLV');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Kandydoza');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Rzęsistkowica');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Świerzb');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Wszawica łonowa');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Ameboza');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Toczeń rumieniowaty układowy');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Twardzina');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Układowe zapalenia naczyń');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Reumatoidalne zapalenie stawów');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Reaktywne zapalenie stawów');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Zesztywniające zapalenie stawów kręgosłupa');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Łuszczycowe zapalenie stawów');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Miażdżyca');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Choroba niedokrwienna serca');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Zaburzenia rytmu i przewodzenia');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Wady serca (wrodzone i nabyte)');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Choroby wsierdzia');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Choroby mięśnia sercowego');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Choroby osierdzia');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Nowotwór serca');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Niewydolność serca');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Nadciśnienie tętnicze');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Nadciśnienie płucne');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Choroby aorty i naczyń obwodowych');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Choroby żył obwodowych');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Żylna choroba zakrzepowo-zatorowa');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Choroby mikrokrążenia');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Choroby naczyń chłonnych');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Jęczmyk');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Ropień powieki');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Półpasiec powieki i gałki ocznej');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Ospica');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Zapalenie brzegów powiek');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Kępki żółte');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Brodawka powieki');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Naczyniak powieki');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Rak powieki');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Niedomykalność szpary powiekowej');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Wywinięcie powieki');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Podwinięcie powieki');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Nieprawidłowy wzrost rzęs');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Tik powieki');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Nadmierne częste mruganie');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Akrofobia');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Alkoholowy zespół abstynencyjny');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Anhedonia');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Anoreksja');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Anxiety neurosis');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Autyzm');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Bezsenność');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Błędne koło');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Bulimia');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Choroba afektywna');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Choroba sieroca');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Ciąża rzekoma');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Depresja');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Depresja poporodowa');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Dysgrafia');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Dyskalkulia rozwojowa');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Dysortografia');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Dystymia');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Egocentryzm');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Fobia');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Hipochondria');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Histeria');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Homofobia');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Jadłowstręt psychiczny');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Klaustrofobia');
INSERT INTO wydarzenia_medyczne ( nazwa) VALUES ( 'Lęk');