INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (1, 1, 19, 11, 'Kolonoskopia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (2, 2, 11, 31, 'Bronchotomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (3, 3, 5, 15, 'Sigmoidoskopia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (4, 4, 17, 25, 'Amputacja');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (5, 5, 13, 58, 'Mukosektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (6, 6, 4, 24, 'Adrenalektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (7, 7, 4, 40, 'Hemisferektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (8, 8, 8, 91, 'Plastyka Heinekego-Mikulicza');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (9, 9, 16, 41, 'Hepatektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (10, 10, 22, 76, 'Operacja Puestowa');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (11, 11, 6, 86, 'Papilotomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (12, 12, 9, 35, 'Diwertikulotomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (13, 13, 9, 38, 'Hemikorporektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (14, 14, 6, 72, 'Operacja Lichtensteina');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (15, 15, 11, 3, 'Laryngoskopia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (16, 16, 4, 34, 'Dekortykacja płuca');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (17, 17, 8, 81, 'Operacja zmiany płci');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (18, 18, 7, 31, 'Bronchotomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (19, 19, 7, 45, 'Kalozotomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (20, 20, 6, 45, 'Kalozotomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (21, 21, 2, 85, 'Owariektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (22, 22, 2, 13, 'Rektoskopia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (23, 23, 16, 61, 'Nefrotomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (24, 24, 17, 10, 'Intestinoskopia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (25, 25, 2, 15, 'Sigmoidoskopia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (26, 26, 20, 83, 'Orchidektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (27, 27, 10, 43, 'Histerektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (28, 28, 19, 5, 'Gastroskopia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (29, 29, 17, 77, 'Operacja Rutkowa');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (30, 30, 11, 16, 'Endoskopia kapsułkowa');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (31, 31, 5, 36, 'Fundoplastyka');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (32, 32, 15, 72, 'Operacja Lichtensteina');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (33, 33, 8, 7, 'Panendoskopia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (34, 34, 15, 86, 'Papilotomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (35, 35, 10, 28, 'Appendektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (36, 36, 20, 20, 'Endoskopia igłowa');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (37, 37, 1, 52, 'Ligacja jajowodu');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (38, 38, 10, 20, 'Endoskopia igłowa');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (39, 39, 1, 2, 'Bronchoskopia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (40, 40, 15, 79, 'Operacja Warrena');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (41, 41, 22, 67, 'Operacja Drapanasa');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (42, 42, 21, 80, 'Operacja Whipple’a');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (43, 43, 11, 28, 'Appendektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (44, 44, 3, 89, 'Penektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (45, 45, 6, 20, 'Endoskopia igłowa');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (46, 46, 8, 49, 'Laminektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (47, 47, 13, 36, 'Fundoplastyka');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (48, 48, 4, 69, 'Operacja Halstedta');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (49, 49, 6, 74, 'Operacja Mogga');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (50, 50, 12, 55, 'Lobotomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (51, 51, 7, 76, 'Operacja Puestowa');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (52, 52, 11, 40, 'Hemisferektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (53, 53, 14, 48, 'Kraniotomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (54, 54, 12, 46, 'Kolektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (55, 55, 6, 4, 'Stroboskopia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (56, 56, 13, 75, 'Operacja Nussa');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (57, 57, 7, 1, 'Profilaktyka');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (58, 58, 20, 79, 'Operacja Warrena');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (59, 59, 15, 42, 'Hipofizektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (60, 60, 21, 58, 'Mukosektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (61, 61, 15, 5, 'Gastroskopia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (62, 62, 20, 3, 'Laryngoskopia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (63, 63, 21, 85, 'Owariektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (64, 64, 19, 69, 'Operacja Halstedta');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (65, 65, 4, 85, 'Owariektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (66, 66, 4, 23, 'Adenomektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (67, 67, 5, 59, 'Nacięcie krocza');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (68, 68, 16, 65, 'Operacja Billrotha');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (69, 69, 14, 57, 'Metastazektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (70, 70, 10, 30, 'Astragalektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (71, 71, 8, 45, 'Kalozotomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (72, 72, 11, 70, 'Operacja Hartmanna');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (73, 73, 15, 76, 'Operacja Puestowa');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (74, 74, 14, 17, 'Kolposkopia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (75, 75, 13, 87, 'Paracenteza');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (76, 76, 9, 70, 'Operacja Hartmanna');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (77, 77, 20, 20, 'Endoskopia igłowa');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (78, 78, 14, 63, 'Ooforektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (79, 79, 22, 86, 'Papilotomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (80, 80, 10, 52, 'Ligacja jajowodu');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (81, 81, 15, 61, 'Nefrotomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (82, 82, 19, 71, 'Operacja Jurasza');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (83, 83, 6, 86, 'Papilotomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (84, 84, 3, 61, 'Nefrotomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (85, 85, 10, 54, 'Lobektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (86, 86, 15, 70, 'Operacja Hartmanna');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (87, 87, 19, 32, 'Cholecystektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (88, 88, 15, 37, 'Gastrektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (89, 89, 11, 84, 'Owarektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (90, 90, 12, 6, 'Ezofagoskopia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (91, 91, 12, 22, 'Adenotomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (92, 92, 8, 51, 'Laryngofisura');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (93, 93, 8, 85, 'Owariektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (94, 94, 11, 69, 'Operacja Halstedta');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (95, 95, 11, 18, 'Cystoskopia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (96, 96, 7, 28, 'Appendektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (97, 97, 20, 25, 'Amputacja');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (98, 98, 18, 71, 'Operacja Jurasza');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (99, 99, 16, 51, 'Laryngofisura');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (100, 100, 18, 82, 'Orbitotomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (101, 101, 21, 21, 'Abdominoplastyka');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (102, 102, 12, 9, 'Duodenoskopia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (103, 103, 19, 14, 'Rektoromanoskopia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (104, 104, 12, 58, 'Mukosektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (105, 105, 9, 38, 'Hemikorporektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (106, 106, 1, 33, 'Cystogastrostomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (107, 107, 2, 1, 'Profilaktyka');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (108, 108, 7, 54, 'Lobektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (109, 109, 9, 39, 'Heminefrektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (110, 110, 14, 23, 'Adenomektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (111, 111, 4, 73, 'Operacja Milesa');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (112, 112, 18, 14, 'Rektoromanoskopia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (113, 113, 3, 36, 'Fundoplastyka');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (114, 114, 20, 16, 'Endoskopia kapsułkowa');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (115, 115, 18, 80, 'Operacja Whipple’a');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (116, 116, 18, 43, 'Histerektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (117, 117, 15, 64, 'Operacja Bassiniego');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (118, 118, 3, 85, 'Owariektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (119, 119, 21, 53, 'Litotrypsja');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (120, 120, 17, 7, 'Panendoskopia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (121, 121, 16, 31, 'Bronchotomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (122, 122, 16, 84, 'Owarektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (123, 123, 3, 27, 'Antromastoidektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (124, 124, 21, 40, 'Hemisferektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (125, 125, 1, 22, 'Adenotomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (126, 126, 18, 26, 'Angioplastyka');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (127, 127, 17, 65, 'Operacja Billrotha');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (128, 128, 21, 43, 'Histerektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (129, 129, 1, 65, 'Operacja Billrotha');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (130, 130, 15, 23, 'Adenomektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (131, 131, 20, 87, 'Paracenteza');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (132, 132, 20, 24, 'Adrenalektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (133, 133, 22, 19, 'Laparoskopia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (134, 134, 12, 74, 'Operacja Mogga');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (135, 135, 8, 27, 'Antromastoidektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (136, 136, 10, 35, 'Diwertikulotomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (137, 137, 14, 54, 'Lobektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (138, 138, 20, 35, 'Diwertikulotomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (139, 139, 19, 2, 'Bronchoskopia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (140, 140, 14, 65, 'Operacja Billrotha');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (141, 141, 13, 51, 'Laryngofisura');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (142, 142, 17, 57, 'Metastazektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (143, 143, 11, 36, 'Fundoplastyka');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (144, 144, 13, 54, 'Lobektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (145, 145, 13, 1, 'Profilaktyka');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (146, 146, 8, 9, 'Duodenoskopia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (147, 147, 4, 76, 'Operacja Puestowa');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (148, 148, 17, 21, 'Abdominoplastyka');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (149, 149, 21, 47, 'Kraniektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (150, 150, 22, 21, 'Abdominoplastyka');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (151, 151, 6, 32, 'Cholecystektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (152, 152, 19, 5, 'Gastroskopia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (153, 153, 11, 9, 'Duodenoskopia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (154, 154, 8, 4, 'Stroboskopia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (155, 155, 2, 67, 'Operacja Drapanasa');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (156, 156, 7, 25, 'Amputacja');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (157, 157, 1, 78, 'Operacja Rydygiera');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (158, 158, 15, 40, 'Hemisferektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (159, 159, 13, 71, 'Operacja Jurasza');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (160, 160, 14, 10, 'Intestinoskopia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (161, 161, 9, 80, 'Operacja Whipple’a');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (162, 162, 1, 41, 'Hepatektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (163, 163, 18, 32, 'Cholecystektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (164, 164, 16, 87, 'Paracenteza');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (165, 165, 21, 29, 'Artroskopia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (166, 166, 15, 47, 'Kraniektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (167, 167, 14, 88, 'Pankreatoduodenektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (168, 168, 10, 85, 'Owariektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (169, 169, 10, 84, 'Owarektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (170, 170, 20, 63, 'Ooforektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (171, 171, 17, 60, 'Nefrektomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (172, 172, 5, 65, 'Operacja Billrotha');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (173, 173, 8, 55, 'Lobotomia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (174, 174, 18, 25, 'Amputacja');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (175, 175, 21, 6, 'Ezofagoskopia');
INSERT INTO skierowania (nr_skierowania, wizyta, specjalizacja, cel_skierowania, opis) VALUES (176, 176, 18, 70, 'Operacja Hartmanna');
ALTER SEQUENCE skierowania_nr_skierowania_seq RESTART 177;